# Generated by Django 5.1.2 on 2024-10-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_user_image_path_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='cardType',
            field=models.IntegerField(default=0),
        ),
    ]
