# Generated by Django 5.1.2 on 2024-10-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_user_cardexpiry_alter_user_balance_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remark',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
