# Generated by Django 5.1.2 on 2024-11-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_payment_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentlog',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
